import type { Graph } from "graphology";
import {
  timestamp,
  header,
  formatNumber,
  table,
  code,
} from "./templates.js";
import { analyzeDeadCode } from "../dead-code/index.js";
import type { DeadSymbol } from "../dead-code/types.js";
import path from "node:path";

export function generateDeadCode(
  graph: Graph,
  projectRoot: string,
  projectName: string
): string {
  const report = analyzeDeadCode(graph, projectRoot, {
    confidence: "low",
    includeTests: false,
    verbose: true,
    stats: true,
    json: true,
  });

  let output = "";
  output += header(`${projectName} - Dead Code Analysis`, 1);
  output += timestamp();
  output += "\n";

  output += header("Summary", 2);
  output += `Total symbols analyzed: **${formatNumber(report.totalSymbols)}**\n\n`;
  output += `Potentially dead symbols: **${formatNumber(report.deadSymbols)}** (${report.deadPercentage.toFixed(1)}%)\n\n`;
  output += `- 🔴 High confidence (definitely dead): **${report.byConfidence.high}**\n`;
  output += `- 🟡 Medium confidence (probably dead): **${report.byConfidence.medium}**\n`;
  output += `- ⚪ Low confidence (might be dead): **${report.byConfidence.low}**\n\n`;

  const estimatedLines = report.deadSymbols * 18;
  output += `Estimated dead code: **~${formatNumber(estimatedLines)} lines**\n\n`;

  const symbolsByConfidence = groupByConfidence(report.symbols);

  if (symbolsByConfidence.high.length > 0) {
    output += generateConfidenceSection(
      "High Confidence",
      "definitely dead",
      symbolsByConfidence.high,
      projectRoot
    );
  }

  if (symbolsByConfidence.medium.length > 0) {
    output += generateConfidenceSection(
      "Medium Confidence",
      "probably dead",
      symbolsByConfidence.medium,
      projectRoot
    );
  }

  if (symbolsByConfidence.low.length > 0) {
    output += generateConfidenceSection(
      "Low Confidence",
      "might be dead",
      symbolsByConfidence.low,
      projectRoot
    );
  }

  output += "\n---\n\n";
  output += "_This document was auto-generated by Depwire. It reflects the current state of the codebase and should be reviewed before taking action._\n";

  return output;
}

function groupByConfidence(symbols: DeadSymbol[]): Record<string, DeadSymbol[]> {
  return symbols.reduce(
    (acc, symbol) => {
      acc[symbol.confidence].push(symbol);
      return acc;
    },
    { high: [], medium: [], low: [] } as Record<string, DeadSymbol[]>
  );
}

function generateConfidenceSection(
  title: string,
  description: string,
  symbols: DeadSymbol[],
  projectRoot: string
): string {
  let output = "";
  output += header(`${title} (${description})`, 2);
  output += `Found **${symbols.length}** symbol${symbols.length === 1 ? "" : "s"}.\n\n`;

  const headers = ["Symbol", "Kind", "File", "Exported", "Reason"];
  const rows = symbols.map((s) => {
    const relativePath = path.relative(projectRoot, s.file);
    return [
      code(s.name),
      s.kind,
      `${relativePath}:${s.line}`,
      s.exported ? "Yes" : "No",
      s.reason,
    ];
  });

  output += table(headers, rows);
  output += "\n";

  return output;
}
