import type { Graph } from "graphology";
import {
  timestamp,
  header,
  formatNumber,
  table,
  code,
} from "./templates.js";
import { analyzeDeadCode } from "../dead-code/index.js";
import type { DeadSymbol } from "../dead-code/types.js";
import path from "node:path";

export function generateDeadCode(
  graph: Graph,
  projectRoot: string,
  projectName: string
): string {
  const report = analyzeDeadCode(graph, projectRoot, {
    confidence: "low",
    includeTests: false,
    verbose: true,
    stats: true,
    json: true,
  });

  let output = "";
  output += header(`${projectName} - Dead Code Analysis`, 1);
  
  // Fix: Provide proper arguments to timestamp()
  const version = process.env.npm_package_version || '0.9.7';
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const fileCount = graph.order; // Total nodes in graph
  const symbolCount = report.totalSymbols;
  output += timestamp(version, date, fileCount, symbolCount);
  output += "\n";

  output += header("Summary", 2);
  
  // Special case: no dead code found
  if (report.deadSymbols === 0) {
    output += "✅ **No dead code detected!**\n\n";
    output += "All symbols in this codebase have at least one dependent. This indicates:\n\n";
    output += "- Clean architecture with no orphaned functions or unused exports\n";
    output += "- Active codebase with well-maintained dependencies\n";
    output += "- Or very few symbols (small project)\n\n";
    output += `Total symbols analyzed: **${formatNumber(report.totalSymbols ?? 0)}**\n\n`;
    output += "---\n\n";
    output += "_This document was auto-generated by Depwire._\n";
    return output;
  }
  
  output += `Total symbols analyzed: **${formatNumber(report.totalSymbols ?? 0)}**\n\n`;
  output += `Potentially dead symbols: **${formatNumber(report.deadSymbols ?? 0)}** (${(report.deadPercentage ?? 0).toFixed(1)}%)\n\n`;
  output += `- 🔴 High confidence (definitely dead): **${report.byConfidence?.high ?? 0}**\n`;
  output += `- 🟡 Medium confidence (probably dead): **${report.byConfidence?.medium ?? 0}**\n`;
  output += `- ⚪ Low confidence (might be dead): **${report.byConfidence?.low ?? 0}**\n\n`;

  const estimatedLines = (report.deadSymbols ?? 0) * 18;
  output += `Estimated dead code: **~${formatNumber(estimatedLines)} lines**\n\n`;

  const symbolsByConfidence = groupByConfidence(report.symbols);

  if (symbolsByConfidence.high.length > 0) {
    output += generateConfidenceSection(
      "High Confidence",
      "definitely dead",
      symbolsByConfidence.high,
      projectRoot
    );
  }

  if (symbolsByConfidence.medium.length > 0) {
    output += generateConfidenceSection(
      "Medium Confidence",
      "probably dead",
      symbolsByConfidence.medium,
      projectRoot
    );
  }

  if (symbolsByConfidence.low.length > 0) {
    output += generateConfidenceSection(
      "Low Confidence",
      "might be dead",
      symbolsByConfidence.low,
      projectRoot
    );
  }

  output += "\n---\n\n";
  output += "_This document was auto-generated by Depwire. It reflects the current state of the codebase and should be reviewed before taking action._\n";

  return output;
}

function groupByConfidence(symbols: DeadSymbol[]): Record<string, DeadSymbol[]> {
  return symbols.reduce(
    (acc, symbol) => {
      acc[symbol.confidence].push(symbol);
      return acc;
    },
    { high: [], medium: [], low: [] } as Record<string, DeadSymbol[]>
  );
}

function generateConfidenceSection(
  title: string,
  description: string,
  symbols: DeadSymbol[],
  projectRoot: string
): string {
  let output = "";
  output += header(`${title} (${description})`, 2);
  output += `Found **${symbols.length}** symbol${symbols.length === 1 ? "" : "s"}.\n\n`;

  const headers = ["Symbol", "Kind", "File", "Exported", "Reason"];
  const rows = symbols.map((s) => {
    const relativePath = path.relative(projectRoot, s.file);
    return [
      code(s.name),
      s.kind,
      `${relativePath}:${s.line}`,
      s.exported ? "Yes" : "No",
      s.reason,
    ];
  });

  output += table(headers, rows);
  output += "\n";

  return output;
}
