/**
 * Markdown template helpers for doc generation
 */

export function header(text: string, level: number = 1): string {
  return `${'#'.repeat(level)} ${text}\n\n`;
}

export function bold(text: string): string {
  return `**${text}**`;
}

export function italic(text: string): string {
  return `*${text}*`;
}

export function code(text: string): string {
  return `\`${text}\``;
}

export function codeBlock(code: string, lang: string = ''): string {
  return `\`\`\`${lang}\n${code}\n\`\`\`\n\n`;
}

export function link(text: string, url: string): string {
  return `[${text}](${url})`;
}

export function unorderedList(items: string[]): string {
  return items.map(item => `- ${item}`).join('\n') + '\n\n';
}

export function orderedList(items: string[]): string {
  return items.map((item, i) => `${i + 1}. ${item}`).join('\n') + '\n\n';
}

export function table(headers: string[], rows: string[][]): string {
  const headerRow = `| ${headers.join(' | ')} |`;
  const separator = `| ${headers.map(() => '---').join(' | ')} |`;
  const dataRows = rows.map(row => `| ${row.join(' | ')} |`).join('\n');
  
  return `${headerRow}\n${separator}\n${dataRows}\n\n`;
}

export function blockquote(text: string): string {
  return `> ${text}\n\n`;
}

export function horizontalRule(): string {
  return `---\n\n`;
}

export function timestamp(version: string, date: string, fileCount: number, symbolCount: number): string {
  return blockquote(`Auto-generated by Depwire ${version} on ${date} | ${fileCount.toLocaleString()} files, ${symbolCount.toLocaleString()} symbols`);
}

/**
 * Format a number with commas for better readability
 */
export function formatNumber(n: number): string {
  return n.toLocaleString();
}

/**
 * Format a percentage with 1 decimal place
 */
export function formatPercent(value: number, total: number): string {
  if (total === 0) return '0.0%';
  return `${((value / total) * 100).toFixed(1)}%`;
}

/**
 * Format an impact level emoji
 */
export function impactEmoji(count: number): string {
  if (count >= 20) return '🔴';
  if (count >= 10) return '🟡';
  if (count >= 5) return '🟢';
  return '⚪';
}
