import { join } from 'path';
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'fs';
import type { DirectedGraph } from 'graphology';
import { getArchitectureSummary } from '../graph/queries.js';

/**
 * Auto-generate .depwire/AGENTS.md after parse.
 *
 * This file gives AI agents a quick-start guide tailored to the actual
 * project structure. It lists module boundaries, key files, and the
 * recommended Depwire MCP tool workflow.
 */
export function generateAgentsMd(
  graph: DirectedGraph,
  projectRoot: string,
  version: string,
): string {
  const summary = getArchitectureSummary(graph);

  // Detect languages from file extensions
  const extCounts = new Map<string, number>();
  graph.forEachNode((_nodeId, attrs) => {
    const ext = attrs.filePath.split('.').pop() || '';
    extCounts.set(ext, (extCounts.get(ext) || 0) + 1);
  });
  const topExts = [...extCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5)
    .map(([ext]) => ext);

  const languageMap: Record<string, string> = {
    ts: 'TypeScript', tsx: 'TypeScript (React)', js: 'JavaScript',
    jsx: 'JavaScript (React)', py: 'Python', go: 'Go', rs: 'Rust',
    java: 'Java', kt: 'Kotlin', rb: 'Ruby', cs: 'C#', cpp: 'C++',
    c: 'C', swift: 'Swift', dart: 'Dart', php: 'PHP', scala: 'Scala',
    vue: 'Vue', svelte: 'Svelte',
  };
  const languages = topExts
    .map(ext => languageMap[ext] || ext.toUpperCase())
    .filter((v, i, a) => a.indexOf(v) === i);

  // Identify top-level directories from file paths
  const dirSet = new Set<string>();
  graph.forEachNode((_nodeId, attrs) => {
    const parts = attrs.filePath.split('/');
    if (parts.length > 1) {
      dirSet.add(parts[0]);
    }
  });
  const topDirs = [...dirSet].sort();

  // Build AGENTS.md content
  const lines: string[] = [];

  lines.push('# AGENTS.md');
  lines.push('');
  lines.push(`> Auto-generated by Depwire v${version}. Re-run \`depwire parse\` to refresh.`);
  lines.push('');
  lines.push('## Project Overview');
  lines.push('');
  lines.push(`- **Languages:** ${languages.join(', ')}`);
  lines.push(`- **Files:** ${summary.fileCount}`);
  lines.push(`- **Symbols:** ${summary.symbolCount}`);
  lines.push(`- **Cross-file edges:** ${summary.edgeCount}`);
  lines.push('');

  if (topDirs.length > 0) {
    lines.push('## Module Structure');
    lines.push('');
    for (const dir of topDirs.slice(0, 15)) {
      lines.push(`- \`${dir}/\``);
    }
    lines.push('');
  }

  if (summary.mostConnectedFiles.length > 0) {
    lines.push('## Key Files (most connections)');
    lines.push('');
    for (const file of summary.mostConnectedFiles) {
      lines.push(`- \`${file.filePath}\` — ${file.connections} connections`);
    }
    lines.push('');
  }

  if (summary.orphanFiles.length > 0) {
    lines.push(`## Orphan Files (${summary.orphanFiles.length} files with no cross-references)`);
    lines.push('');
    const shown = summary.orphanFiles.slice(0, 10);
    for (const file of shown) {
      lines.push(`- \`${file}\``);
    }
    if (summary.orphanFiles.length > 10) {
      lines.push(`- ... (${summary.orphanFiles.length - 10} more)`);
    }
    lines.push('');
  }

  lines.push('## Depwire MCP Workflow');
  lines.push('');
  lines.push('Before modifying any file, run:');
  lines.push('');
  lines.push('```');
  lines.push('connect_repo .');
  lines.push('get_file_context <file>     # understand symbols & dependents');
  lines.push('impact_analysis <file>      # blast radius');
  lines.push('```');
  lines.push('');
  lines.push('After changes:');
  lines.push('');
  lines.push('```');
  lines.push('verify_change --file <file> # check import safety');
  lines.push('get_health_score            # confirm no regression');
  lines.push('affected_files <file>       # find tests to run');
  lines.push('```');
  lines.push('');
  lines.push('For destructive operations (move/delete/rename):');
  lines.push('');
  lines.push('```');
  lines.push('simulate_change --type <action> --target <file>');
  lines.push('```');
  lines.push('');
  lines.push('Full prompt: `depwire prompt` or `depwire prompt --tool claude`');
  lines.push('');

  return lines.join('\n');
}

/**
 * Write AGENTS.md to .depwire/ directory.
 * Creates the directory if needed.
 */
export function writeAgentsMd(
  graph: DirectedGraph,
  projectRoot: string,
  version: string,
): void {
  const depwireDir = join(projectRoot, '.depwire');
  const agentsPath = join(depwireDir, 'AGENTS.md');

  const content = generateAgentsMd(graph, projectRoot, version);

  try {
    if (!existsSync(depwireDir)) {
      mkdirSync(depwireDir, { recursive: true });
    }

    // Only write if content changed (avoid unnecessary git noise)
    if (existsSync(agentsPath)) {
      const existing = readFileSync(agentsPath, 'utf-8');
      if (existing === content) return;
    }

    writeFileSync(agentsPath, content, 'utf-8');
    console.error('\x1b[2mGenerated .depwire/AGENTS.md\x1b[0m');
  } catch (err) {
    // Non-fatal — don't fail the parse because of AGENTS.md
    console.error(`Warning: Could not write AGENTS.md: ${err instanceof Error ? err.message : err}`);
  }
}
